/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 
package GUI;

import Audio.AudioPlayer;
import java.util.*;
import javax.swing.JOptionPane;

import Logic.*;
/**
 *Implementa a interface gráfica do menu de Login.
 * @author lpro1612
 */
public class LoginGUI extends javax.swing.JFrame {

    AudioPlayer songInic = new AudioPlayer();
    AudioPlayer butSoundLog = new AudioPlayer();
    AudioPlayer butMainSound = new AudioPlayer();
    
    public void inicSound(){
        songInic.getName("inic.wav");
        songInic.soundBegin();
        songInic.start();
        songInic.loop();
    }
    
    public void butSoundLog(){
        butSoundLog.getName("login.wav");
        butSoundLog.soundBegin();
    }
    
    public void butMainSound(){
        butMainSound.getName("button2.wav");
        butMainSound.soundBegin();
    }
    
    /**
     * Cria e inicializa um novo formulário de login.
     */
    public LoginGUI() {
        
        inicSound();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PasswordField = new javax.swing.JPasswordField();
        Username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        lostPassword = new javax.swing.JButton();
        createAnAccount = new javax.swing.JButton();
        UsernameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        Login = new javax.swing.JButton();
        Mute = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");

        jPanel1.setLayout(null);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField);
        PasswordField.setBounds(160, 170, 260, 30);

        Username.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Username.setForeground(new java.awt.Color(244, 240, 240));
        Username.setText("Username:");
        jPanel1.add(Username);
        Username.setBounds(55, 140, 100, 20);

        password.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password.setForeground(new java.awt.Color(254, 242, 242));
        password.setText("Password:");
        jPanel1.add(password);
        password.setBounds(52, 170, 100, 20);

        lostPassword.setText("Lost Password?");
        lostPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(lostPassword);
        lostPassword.setBounds(220, 310, 170, 23);

        createAnAccount.setText("Create an account");
        createAnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(createAnAccount);
        createAnAccount.setBounds(220, 260, 170, 23);
        jPanel1.add(UsernameField);
        UsernameField.setBounds(160, 130, 260, 30);

        jPanel2.setLayout(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(100, 360, 480, 80);

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("BaShip");
        jPanel2.add(label1);
        label1.setBounds(210, 41, 130, 40);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel2.add(Login);
        Login.setBounds(260, 220, 130, 23);

        Mute.setText("Mute/Unmute");
        Mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuteActionPerformed(evt);
            }
        });
        jPanel2.add(Mute);
        Mute.setBounds(670, 10, 110, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/batalha--naval-c810b.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 0, 800, 450);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-20, 0, 820, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        butSoundLog();
        butSoundLog.start();
        
         String username=UsernameField.getText();
          if(username.isEmpty()){
            JOptionPane.showMessageDialog(null,"Username Field is empty"); 
            return;
          }
          String password=new String(PasswordField.getPassword());
         if(password.isEmpty()){
            JOptionPane.showMessageDialog(null,"Password Field is empty");
            return;
         } 
         Login log = new Login(username, password);
         if(log.checkLogin()==true){
                songInic.pause();
                LoginGUI.this.setVisible(false);
                MainMenuGUI menu = new MainMenuGUI();
                menu.setVisible(true);
         }
         
    }//GEN-LAST:event_LoginActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void createAnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAnAccountActionPerformed
        butMainSound();
        butMainSound.start();
        songInic.pause();
        RegisterGUI reg = new RegisterGUI();
        reg.setVisible(true);
        LoginGUI.this.setVisible(false);
    }//GEN-LAST:event_createAnAccountActionPerformed

    private void lostPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostPasswordActionPerformed
        butMainSound();
        butMainSound.start();
        songInic.pause();
        LoginGUI.this.setVisible(false);
        LostPasswordGUI lp = new LostPasswordGUI();
        lp.setVisible(true);
    }//GEN-LAST:event_lostPasswordActionPerformed

    private void MuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuteActionPerformed
        // TODO add your handling code here:
        if(songInic.getRun()==1)
            songInic.pause();
        else{
            songInic.start();
            songInic.loop();
        }
    }//GEN-LAST:event_MuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton Mute;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton createAnAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private javax.swing.JButton lostPassword;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
